#!/bin/bash
SCRIPT_DIR=$(dirname $0)
#./ecl-test setup --excludeclass=3rdparty,embedded,spray --pq=10 --server 34.66.125.65

#./ecl-test setup --excludeclass=3rdparty,embedded,spray --pq=10 --server a95fcae1419214aa98d44d43b6b5a43d-1580568255.us-east-1.elb.amazonaws.com


# hpcc-dev-160
#server=a4375fcb07d314446b3036e4a5a3ded0-867327524.us-east-1.elb.amazonaws.com

#eks-hpcc-1

# eks-hpcc-1
#server=ab619426a27cf48cc8295221b53958ba-716284310.us-east-1.elb.amazonaws.com
server=
[ -n "$1" ] && server=$1

SRC_DIR=./HPCC-Platform
[ -n "$2" ] && SRC_DIR=$2

#server=localhost


#ecl run thor -s ${server}  <ecl file path>
#${SCRIPT_DIR}/test-playground.sh -d $SRC_DIR -s $server -t "hthor roxie thor" | tee -a test.out
#${SCRIPT_DIR}/test-playground.sh -d $SRC_DIR -s $server -t "hthor thor" | tee -a test.out
${SCRIPT_DIR}/test-playground.sh -d $SRC_DIR -s $server -t "hthor thor roxie-workunit" | tee -a test.out
