#!/bin/bash
SCRIPT_DIR=$(dirname $0)
server=
[ -n "$1" ] && server=$1

SRC_DIR=/home/hpcc/HPCC-Platform
[ -n "$2" ] && SRC_DIR=$2

LOG_DIR=/home/hpcc/tmp
[ -n "$3" ] && LOG_DIR=$3

echo "${SCRIPT_DIR}/test-playground2.sh -d $SRC_DIR -s $server -t \"hthor thor roxie-workunit\" | tee ${LOG_DIR}/playground.out"
${SCRIPT_DIR}/test-playground2.sh -d $SRC_DIR -s $server -t "hthor thor roxie-workunit" | tee ${LOG_DIR}/playground.out
