name: Send Email

# https://reedelsevier.sharepoint.com/sites/OG-CoP-Cloud/SitePages/8wpjrztv.aspx?web=1&e=5_LyB_BCkU2BsQbCVyk-2g&at=17&OR=Teams-HL&CT=1654889967823&params=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA1MDEwMTAwOSJ9
# https://topdesk.b2b.regn.net/tas/public/ssp/content/serviceflow?unid=650fdab70bad482f878b5b829dec715b
# After login go to myaccount.google.com/apppasswords to set app password
#
on:
  workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  Send-email:

    name: "Send email"
    env:
      GITHUB_ORG: xwang2713
      GITHUB_REPO: github-action-hpcc-terraform
      GITHUB_REPO_BRANCH: main
      WF_YAML_FILE: az-bvt.yml

    runs-on: Ubuntu-22.04
    steps:
    - name: 'Test send email'
      run: |
        ip addr show
        cat << EOF > bvt.out
        ECL Setup

        Playground
        EOF


#   - name: Send email
#      run: |
#        sudo apt install wget -y
#        wget https://github.com/hpcc-systems/HPCC-Platform/releases/download/community_9.8.32-rc1/BVT.result
#        sudo apt install mailutils -y
#        cat BVT.result | mail -s "ming test from Github Action" xiaoming.wang@lexisnexisrisk.com

    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        #server_address: smtp.office365.com
        #server_address: Apollo.lexisnexisrisk.com
        #server_port: 25
        server_address: smtp.gmail.com
        # port465 for SSL or 587 for TLS
        #server_port: 587
        server_port: 465
        #server_address: smtp-mail.outlook.com
        #, // Use true for port 465, false for all other ports
        secure: true
        #secure: false
        # Optional (recommended) mail server username:
        #username: ${{secrets.MAIL_USERNAME}}
    #    # Optional (recommended) mail server password:
        username: "hpcctest7@gmail.com"
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Github Actions BVT result
        to: xiaoming.wang@lexisnexisrisk.com
        #to: bryan.cabrera@lexisnexisrisk.com
        from: hpcctest7@gmail.com
        #from: xiaoming.wang@lexisnexisrisk.com
        html_body: file://bvt.out
        ignore_cert: true
    #    #cc:
    #    #bcc:
    #    ignore_cert: true
    #    #convert_markdown: true
    #    #attachments: attachments.zip,git.diff,./dist/static/*.js
    #    priority: low
    #    #nodemailerlog: false
    #    #nodemailerdebug: false

