name: Upload Test Result to a Repo release

on:
  workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  upload-result:

    name: "Upload Result"
    env:
      GITHUB_ORG: hpcc-systems
      GITHUB_REPO: HPCC-Platform
      RESULT_FILE: test.out
      RELEASE_REF: community_9.12.2-rc1

    runs-on: Ubuntu-22.04
    steps:
    - name: 'Create a dummy result file'
      run: |
        echo "Test result" >  ${{ env.RESULT_FILE }}

    - name: "Upload result file to the repo release"
      continue-on-error: true
#      uses: svenstaro/upload-release-action@v2
#      with:
#        file: ${{ env.RESULT_FILE }}
#        asset_name: "BVT.result"
#        tag: "community_9.12.0-rc1"
#        overwrite: true
#        repo_token: ${{ secrets.MING_GITHUB_TOKEN }}
      uses: xresloader/upload-to-github-release@main
      #env:
      #  GITHUB_TOKEN: ${{ secrets.MING_GITHUB_TOKEN }}
      with:
        file: ${{ env.RESULT_FILE }}
        tag_name: ${{ env.RELEASE_REF }}
        overwrite: true
        tags: true
        target_owner: ${{ env.GITHUB_ORG }}
        target_repo: ${{ env.GITHUB_REPO }}
        token: ${{ secrets.MING_GITHUB_TOKEN }}
